export default [
  'Você precisa ter pelo menos 13 anos de idade para usar o Serviço.',
  'Você não pode publicar fotos ou outros tipos de conteúdo por meio do Serviço que sugiram violência, nudez, discriminação, atos ilegais, transgressões, ódio, pornografia ou sexo.',
  'Você é responsável por qualquer atividade que ocorra através de sua conta e concorda em não vender, transferir, licenciar ou ceder sua conta, seus seguidores, seu nome de usuário ou qualquer direito da conta. Com exceção de pessoas ou entidades que estejam expressamente autorizadas a criar contas em nome de seus empregadores ou clientes, o Toakee proíbe a criação de, e você concorda que não irá criar, uma conta para qualquer outra pessoa além de você mesmo. Você também declara que todas as informações fornecidas por você ou fornecidas ao Toakee no momento do cadastro e em qualquer outro momento são verdadeiras, precisas, atuais e completas e você concorda em atualizar suas informações quando necessário para manter sua veracidade e exatidão.',
  'Você é responsável por manter sua senha em sigilo e protegida.',
  'Você não pode difamar, perseguir, praticar bullying, praticar abuso , assediar, ameaçar, intimidar ou fingir ser pessoas ou entidades. Você não deve publicar informações privadas ou confidenciais através do Serviço, incluindo, entre outras coisas, as informações do seu cartão de crédito ou de outra pessoa, número do CPF ou outros números de identidade nacional, números de telefone que não sejam conhecidos publicamente ou endereços de email que não sejam conhecidos publicamente.',
  'Você não pode usar o Serviço para nenhuma finalidade ilegal ou não autorizada. Você concorda em obedecer todas as leis, regras e normas (por exemplo, federais, estaduais e municipais) aplicáveis ao seu uso do Serviço e seu Conteúdo (definido abaixo), incluindo, entre outras coisas, leis de direitos autorais.',
  'O Toakee, nem terceiros, fornece qualquer garantia quanto à precisão, pontualidade, integridade das informações e materiais encontrados ou oferecidos neste site para qualquer propósito específico. Você reconhece que tais informações e materiais podem conter imprecisões ou erros e nós excluímos expressamente a responsabilidade por tais imprecisões ou erros na medida máxima permitida por lei.',
    'O uso de qualquer informação ou material neste site é por sua própria conta e risco. Você tem a responsabilidade de garantir que quaisquer produtos, serviços ou informações disponíveis através deste site atinjam os suas exigências específicas.',
    'Você é o único responsável por sua conduta e por qualquer dado, texto, arquivos, informação, nomes de usuário, imagens, gráficos, fotos, perfis, links e outro conteúdo ou materiais (coletivamente, "Conteúdo") que você envie, publique ou exiba no Serviço ou por meio dele.',
    'Você não pode mudar, modificar, adaptar ou alterar o Serviço ou mudar, modificar ou alterar outro site de forma que fique implícito falsamente que ele está associado ao Serviço ou ao Toakee.',
    'Você não pode interferir ou interromper o Serviço ou servidores ou redes conectados ao Serviço, inclusive por meio de transmissão de worms, vírus, spyware, malware ou qualquer outro código de natureza destrutiva ou disruptiva. Você não pode inserir conteúdo ou código ou, então, alterar ou interferir na forma como qualquer página do Toakee é renderizada ou exibida no navegador ou dispositivo de um usuário.',
    'A violação desses Termos de Uso pode, a exclusivo critério do Toakee, resultar no encerramento da sua conta do Toakee. Você entende e concorda que o Toakee não pode e não será responsável pelo Conteúdo publicado no Serviço e você usa o Serviço por sua conta e risco. Se você violar o texto ou a intenção desses Termos de Uso, ou se, de outra forma, gerar risco ou possível exposição legal para o Toakee, nós podemos interromper o fornecimento do Serviço, na sua totalidade ou parcialmente, para você.',
];
