export default [
  'O Toakee administra a plataforma. O usuários cadastram os eventos e publicam seus conteúdos.',
  'Você se compromete em publicar eventos ou quaisquer conteúdos que sejam verdadeiros e com informações completas. Assim, é de responsabilidade do usuário comunicar com exatidão informações como local, data, horário, valores, atrações, serviços oferecidos, contato, política de cancelamento, política de meia-entrada, restrição de faixa etária e qualquer outra informação que seja relevante para os consumidores ou, ainda, para a validação da realização dos eventos.',
  'Você se compromete em publicar eventos ou quaisquer conteúdos que tenha o direito e capacidade de cumprir. Assim, o organizador assume que os eventos ou conteúdos publicados têm todos os seus trâmites finalizados junto a atrações, local, patrocinadores, fornecedores, órgãos públicos e qualquer outra parte interessada e que é capaz e irá entregar tudo o que foi anunciado.',
  'Você confirma que tem direitos sobre o evento ou conteúdo publicado e que não está infringindo nenhuma patente, marca registrada ou direito autoral de qualquer pessoa ou entidade.',
  'Você não pode publicar eventos ou quaisquer conteúdos que sejam ilegais, racistas, ameaçadores, difamatórios, obscenos, vulgares ou invasivos da privacidade alheia;',
  'Você tem total responsabilidade sobre os links e redirecionamentos postados na descrição da página pública do evento. O Toakee não tem responsabilidade sobre os mesmos e não atesta sua veracidade ou confiabilidade;',
  'Você tem a responsabilidade de atualizar as informações do evento publicado no Toakee em casos de cancelamento de evento, cancelamento de atração, alteração de data, alteração de local ou qualquer outra alteração relevante referente ao seu evento.',
  'Ser o único responsável pelos eventos e conteúdos cadastrados, isentando o Toakee de qualquer responsabilidade sobre os mesmos. O Toakee não é uma organizadora de eventos. Fornecemos a plataforma para que os organizadores divulguem e gerenciem seus eventos.',
  'O Toakee somente pode ser utilizado para a divulgação e gerenciamento de eventos. Não é permitido anunciar, fazer publicidade de, e divulgar qualquer produto, serviço, pessoa, estabelecimento ou algo que não seja um evento.',
  'Não respeitar as regras para cadastramento de evento resulta na não publicação do mesmo e o Toakee poderá suspender ou encerrar a conta do organizador e recusar a prover quaisquer de nossos serviços.',
];
