export default [
  '<p>Bem-vindo ao Toakee ("Toakee", "nós", "nos" ou "nosso"). O Toakee oferece a você uma forma prática e divertida de encontrar, criar e compartilhar eventos através da nossa plataforma de compartilhamento de conteúdo. Nela você pode adicionar eventos na sua agenda, convidar amigos para eventos, e compartilhar momentos vivenciados nesses eventos!</p>',
  '<p>Nossa Política de Privacidade explica como nós coletamos, usamos, compartilhamos e protegemos as informações relacionadas a nossos serviços móveis, site da Web e qualquer software fornecido em ou associado aos serviços do Toakee (coletivamente, o <b>"Serviço"</b>), e suas escolhas sobre a coleta e o uso de suas informações.</p>',
  '<p>Ao usar o nosso Serviço, você entende e concorda que estamos oferecendo uma plataforma para você publicar conteúdo, incluindo fotos, comentários e outros materiais (<b>"Conteúdo do Usuário"</b>) no Serviço e para compartilhar o Conteúdo do Usuário publicamente. Isso significa que outros Usuários podem pesquisar por, ver, usar ou compartilhar qualquer Conteúdo do usuário que você disponibilize publicamente através do Serviço, em consonância com os termos e condições desta Política de Privacidade e nossos Termos de Uso (que podem ser encontrados em <a href="/termos-de-uso">Termos de Uso</a>).</p>',
  '<p>Nossa Política se aplica a todos os visitantes, usuários e outros que acessam o Serviço (<b>"Usuários"</b>).</p>',
  '<p>Quando a definição de um termo não aparecer nesta Política de Privacidade (tais como "Anúncio", "Propriedade", "Conteúdo", "Serviços", etc.) a estes serão atribuídos as definições previstas em nossos Termos de Serviço.</p>',
  '<p>"Informação Agregada" significa informação sobre todos os nossos usuários ou grupos ou categorias específicas de usuários que nós combinamos de modo a não identificar ou fazer referência a um usuário individual.</p>',
  '<p>"Controlador de Dados" significa Toakee, a empresa responsável pelo uso e processamento de Informações Pessoais.</p>',
  '<p>"Informações Pessoais" significa informações relacionadas a uma pessoa que é ou possa ser identificada seja por meio de tais informações ou por meio de tais informações em conjunto com outras informações que estejam, ou possam vir a estar, em posse do Controlador de Dados.</p>',
];
