export default [
  'Nós nos reservamos o direito de modificar ou encerrar o Serviço ou o seu acesso ao Serviço por qualquer motivo, sem aviso prévio, a qualquer momento e sem obrigações com você.',
  'Nós nos reservamos o direito, a nosso exclusivo critério, de alterar esses Termos de Uso ("Termos Atualizados") de tempos em tempos. A menos que façamos uma alteração por motivos jurídicos ou administrativos, forneceremos um aviso com razoável antecedência antes de os Termos Atualizados entrarem em vigor. Você concorda que nós podemos notificá-lo sobre os Termos Atualizados publicando-os no Serviço, e que o seu uso do Serviço após a data de efetivação dos Termos Atualizados (ou envolvimento em determinada conduta que nós podemos especificar) constitui seu consentimento dos Termos Atualizados. Portanto, você deve analisar esses Termos de Uso e quaisquer Termos Atualizados antes de usar o Serviço. Os Termos Atualizados entrarão em vigor no momento da publicação, ou em data posterior conforme pode ter sido especificado nos Termos Atualizados, e se aplicarão ao seu uso do Serviço deste momento em diante. Esses Termos de Uso regerão todas as disputas que surjam após a data de efetivação dos Termos Atualizados.',
  'Nós nos reservamos o direito de recusar o acesso ao Serviço a qualquer pessoa, por qualquer motivo, a qualquer momento.',
  'Nós podemos, mas não temos a obrigação de, remover, editar, bloquear e/ou monitorar Conteúdo ou contas com Conteúdo que nós determinamos, a nosso exclusivo critério, que viola esses Termos de Uso.',
  'Podem existir links do Serviço, ou de comunicações que você recebe do Serviço, para sites ou recursos de terceiros. Também podem existir links para sites ou recursos de terceiros em imagens ou comentários dentro do Serviço. O Serviço também inclui conteúdo de terceiros que nós não controlamos, mantemos ou apoiamos. O Toakee não controla nenhum desses serviços de terceiros ou qualquer conteúdo deles. Você reconhece e concorda expressamente que o Toakee não é, de forma alguma, responsável por esses serviços ou recursos de terceiros. SUA CORRESPONDÊNCIA E NEGÓCIOS COM TERCEIROS OBTIDOS ATRAVÉS DO SERVIÇO SÃO SOMENTE ENTRE VOCÊ E O TERCEIRO. ',
  'Você concorda que você é responsável por todas as cobranças de dados a que você ficar sujeito através do uso do Serviço.',
  'Nós proibimos o rastreamento, scraping, armazenamento em cache ou, de qualquer outro modo, o acesso a qualquer conteúdo no Serviço através de meios automatizados, incluindo, entre outras coisas, perfis e fotos de usuários (exceto como resultado de protocolos ou tecnologias de mecanismos de busca padrão com a autorização expressa do Toakee).',
  'O Toakee não reivindica a propriedade de nenhum Conteúdo que você publica no Serviço ou através dele.',
  'O nome e o logotipo do Toakee são marcas registradas do Toakee, e não devem ser copiados, imitados ou usados, em sua totalidade ou parcialmente, sem a autorização prévia por escrito do Toakee. Além disso, todos os cabeçalhos de página, elementos gráficos personalizados, ícones de botões e scripts são marcas de serviço, marcas comerciais e/ou conjunto-imagem do Toakee, e não podem ser copiados, imitados ou usados, em sua totalidade ou parcialmente, sem a autorização prévia por escrito do Toakee.',
  'Você concorda que o Toakee não é responsável por, e não pode apoiar, Conteúdo publicado dentro do Serviço. O Toakee não tem nenhuma obrigação de pré-selecionar, monitorar, editar ou remover qualquer Conteúdo. Se o seu Conteúdo viola esses Termos de Uso, você pode arcar com a responsabilidade legal por esse Conteúdo.',
];
